apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: deb-vm-3
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        #kubevirt.io/size: small
        kubevirt.io/domain: deb-vm-3
    spec:
      domain:
        features:
          acpi: {}
          apic: {}
          smm: {}
        cpu:
          cores: 4
          threads: 1
          sockets: 1
          maxSockets: 1
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2048M
            cpu: 1
          limits:
            cpu: 4
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              user: fedora
