apiVersion: v1
kind: Service
metadata:
  name: fedora-vm-svc
spec:
  type: LoadBalancer
    #loadBalancerIP: 34.51.37.188
  ports:
    - port: 22
      targetPort: 22
      name: ssh
  selector:
    kubevirt.io/domain: fedora-vm
