apiVersion: v1
kind: Service
metadata:
  name: fedora-vm-svc
spec:
  type: ClusterIP
  ports:
    - port: 1
      targetPort: 1
      name: icmp
    - port: 22
      targetPort: 22
      name: ssh
  selector:
    kubevirt.io/domain: fedora
