apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    migrations:
      disableTLS: true
      allowAutoConverge: true
      allowPostCopy: true
      completionTimeoutPerGiB: 100
    developerConfiguration: {}
  customizeComponents:
  imagePullPolicy: Always
  workloadUpdateStrategy: {}
