apiVersion: v1
kind: Service
metadata:
  name: cirros-vm-service
spec:
  type: LoadBalancer
  ports:
    - port: 22        # Port to expose on the LoadBalancer
      targetPort: 22  # Port on the VM
      protocol: TCP
      name: ssh
  selector:
    kubevirt.io/domain: cirros  # This matches the label we set on the VM
